### ISSUE TITLE
Captcha Sometimes not working

### ISSUE THREAD

**Issue by Jambo199** [thejoabo/autofishbot#77]
For some reason today, as i started autofishing, it got a captcha but it was unable to get it right at all, what should i do?

**Comment by thejoabo** [comment]
Hello @Jambo199 , I've been very short in time past few weeks so I couldn't give much attention to this project, but they released this note on their official Discord server:
![image](https://user-images.githubusercontent.com/49594896/215296651-047f043d-c73e-4ef2-b959-9f08eec9d866.png)
Maybe your issue is related to that. Another reason why this might be happening is the API that I'm using to solve the OCR challenges, you can check the API status at any time here: https://status.ocr.space/

Note: It's always very useful to send screenshots/logs of the problem so I can properly identify the problem.

**Comment by Jambo199** [comment]
Also is there anyway we could keep in touch on discord (Jambo199#8069), i would like to know more about ur project

**Comment by thejoabo** [comment]
I sent you a friend request there (my discord tag is #3284)
