### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by rominmusa** [thejoabo/autofishbot#79]
For some reason proxy from the shared site is failing to detect

**Comment by thejoabo** [comment]
Hello @rominmusa, they must be valid HTTPS. Also, I purposely choose online public sites to "validate" the proxies, because they detect IP's that are restricted/banned from websites (returning the 403 error and not allowing the usage of that IP). This is useful to avoid account bans from Discord's server. Try a private/less known service to avoid those issues. 

Note: I plan to change this proxy function in the future to facilitate setting it up. Now it's too sketchy.
