### ISSUE TITLE
How Do I REDUCE THE NUMBER OF SHORT COOLDOWN COMMANDS I want to reduce the short commands by a bit as I want to lowkey maximize the number of commands I run

### ISSUE THREAD

**Issue by Dasher-Minecraft** [thejoabo/autofishbot#85]

**Comment by thejoabo** [comment]
Hello @Dasher-Minecraft, I don't know if I understand it correctly, please help me to comprehend your demand:

Assumption:
You are referring strictly to the **/fish** command and "_fish again_" button interaction.

Questions:
1. You want to remove the randomization of the cooldowns to have a linear set of values, in order to preserve the raw base cooldown ?
2. You want reduce the base cooldown and keep the randomization ?

If 1:
You will have to modify the source code to return 0 on the _new()_ function in the **cooldown.py** file, to do so replace the _new()_ function with:
```python
def new(self) -> float:
    return 0.0
```
Note: **this is not recommended at all**, you will loose the gaussian function purpose, which is in place to "bypass" their analysis to detect players using automation tools.

If 2:
You will have to modify the **USER_COOLDOWN** parameter in your config file to `2.0` (which is the minimum allowed by VF services).
