### ISSUE TITLE
object of none

### ISSUE THREAD

**Issue by UwUTheDog** [thejoabo/autofishbot#93]
![image](https://user-images.githubusercontent.com/125784363/219925703-13cc35e3-c2bd-42fd-8dd9-e916a30a7e39.png)
Get this error when starting it. followed steps properly.

**Comment by Maxhem2** [comment]
Reinstall Python and add ADD PATH option might help

**Comment by UwUTheDog** [comment]
Did all that and it still gives the error 

![image](https://user-images.githubusercontent.com/125784363/219950502-e0e764dc-37a6-4cb4-a143-406d13d9f3b6.png)

**Comment by UwUTheDog** [comment]
![image](https://user-images.githubusercontent.com/125784363/219950624-7ec9e537-0cb1-446b-aaf3-58256fbf5813.png)

**Comment by Maxhem2** [comment]
Have you made sure your config is filled correctly?

**Comment by UwUTheDog** [comment]
discord.gg/cowsgomoo You can litterly see your self on share screen everythings set correctly. i will litterly pay you to make it work if you think you know better.

**Comment by Maxhem2** [comment]
Add me on discord R3gas#8663 I'd like to take a look at it. No need to pay anything

**Comment by thejoabo** [comment]
Hello @UwUTheDog , my best guess would be incorrect token or something related to your authorization thought Discord's gateway (which I use to receive all the new events addressed to that token) and, since you are not being authorized, it tries to get key-values from a **None** type event returned from the gateway (crashing the bot). 

I can't say for sure what exactly is going on, but I was able to replicate your issue by setting a wrong value to my token parameter as you can see here:

![image](https://user-images.githubusercontent.com/49594896/220163330-562eb93a-8993-47bb-852a-f7470ba5d4fb.png)

**Comment by UwUTheDog** [comment]
Fixed now i had to get my token a diff way it wasnt showing the real one up i recomend this site
https://linuxhint.com/get-discord-token/

**Comment by thejoabo** [comment]
Hello @UwUTheDog , I'm glad it worked out then. Just for closure, there is already a guide about how to get the token and other important topics on this repo: [FAQ](https://github.com/thejoabo/autofishbot/blob/main/assets/faq.md#user_token-).
